#!/bin/bash
#PBS -S /bin/bash
#PBS -j oe
#PBS -V
#PBS -l nodes=1:ppn=8:gpus=1
project_dir=/home/xyzhang/research/ADBCVUMPS.jl
julia --project=${project_dir} ${project_dir}/job/Kitaev.jl --D 4 --chi 20 --folder ~/../../data1/xyzhang/ADBCVUMPS/Kitaev_complex/