#!/bin/bash									        
#SBATCH --partition=a100							#任务提交到分区
#SBATCH --nodes=1								    #使用一个节点
#SBATCH --gres=gpu:1		                        #使用1块卡
#SBATCH --time=9999:00:00							#总运行时间，单位小时
module load julia-1.7.1
project_dir=~/research/AD-Kitaev
julia --project=${project_dir} ${project_dir}/job/K_J_Γ_Γ′.jl --K -0.0 --J 0.0 --Γ 1.0 --Γ′ 0.0 --field 0.0 --Ni 1 --Nj 2 --D 6 --chi 100 --folder ~/../../data/xyzhang/ADBCVUMPS/ --type _random